name: Linting

on:
  push:
    branches:
      - master
      - v8-json-rpc
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: flake8
        run: flake8 custom_components
      - name: isort
        run: isort --diff --check custom_components
      - name: Black
        run: black --line-length 88 --diff --check custom_components
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
